/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CommentModel {
    'commentId'?: number | null;
    'comment'?: string | null;
    'userId'?: number | null;
    'conversationId'?: number | null;
    'task'?: string | null;
    'vote'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "commentId",
            "baseName": "comment_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "task",
            "baseName": "task",
            "type": "string",
            "format": ""
        },
        {
            "name": "vote",
            "baseName": "vote",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommentModel.attributeTypeMap;
    }

    public constructor() {
    }
}

