/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommentResponseMessage } from '../models/CommentResponseMessage';
import { ConversationResponseMessage } from '../models/ConversationResponseMessage';
import { UserResponseMessage } from '../models/UserResponseMessage';
import { HttpFile } from '../http/http';

export class Detail2 {
    'id': number;
    'email': string;
    'role': string;
    'title': string;
    'description': string;
    'creatorId': number;
    'moderation'?: boolean;
    'createDate': string;
    'comment': string;
    'userId': number;
    'conversationId': number;
    'moderated'?: boolean;
    'approved'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "creatorId",
            "baseName": "creator_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "moderation",
            "baseName": "moderation",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createDate",
            "baseName": "create_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "moderated",
            "baseName": "moderated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "approved",
            "baseName": "approved",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Detail2.attributeTypeMap;
    }

    public constructor() {
    }
}

