# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from litepolis_client.api.conversations_api import ConversationsApi


class TestConversationsApi(unittest.TestCase):
    """ConversationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConversationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_conversation_api_v1_secure_conversations_post(self) -> None:
        """Test case for create_conversation_api_v1_secure_conversations_post

        Create Conversation
        """
        pass

    def test_delete_conversation_api_v1_secure_conversations_cid_delete(self) -> None:
        """Test case for delete_conversation_api_v1_secure_conversations_cid_delete

        Delete Conversation
        """
        pass

    def test_get_all_conversations_api_v1_secure_conversations_all_get(self) -> None:
        """Test case for get_all_conversations_api_v1_secure_conversations_all_get

        Get All Conversations
        """
        pass

    def test_get_conversation_api_v1_secure_conversations_cid_get(self) -> None:
        """Test case for get_conversation_api_v1_secure_conversations_cid_get

        Get Conversation
        """
        pass

    def test_update_conversation_api_v1_secure_conversations_put(self) -> None:
        """Test case for update_conversation_api_v1_secure_conversations_put

        Update Conversation
        """
        pass


if __name__ == '__main__':
    unittest.main()
