# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from litepolis_client.api.api_keys_api import APIKeysApi


class TestAPIKeysApi(unittest.TestCase):
    """APIKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIKeysApi()

    def tearDown(self) -> None:
        pass

    def test_update_usertoken_api_v1_secure_users_renew_put(self) -> None:
        """Test case for update_usertoken_api_v1_secure_users_renew_put

        Update Usertoken
        """
        pass


if __name__ == '__main__':
    unittest.main()
