# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from litepolis_client.api.comments_api import CommentsApi


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_comment_api_v1_secure_comments_post(self) -> None:
        """Test case for create_comment_api_v1_secure_comments_post

        Create Comment
        """
        pass

    def test_delete_comment_api_v1_secure_comments_cid_delete(self) -> None:
        """Test case for delete_comment_api_v1_secure_comments_cid_delete

        Delete Comment
        """
        pass

    def test_get_comments_api_v1_secure_comments_cid_get(self) -> None:
        """Test case for get_comments_api_v1_secure_comments_cid_get

        Get Comments
        """
        pass

    def test_get_comments_for_moderation_api_v1_secure_comments_cid_moderate_get(self) -> None:
        """Test case for get_comments_for_moderation_api_v1_secure_comments_cid_moderate_get

        Get Comments For Moderation
        """
        pass

    def test_update_comment_api_v1_secure_comments_put(self) -> None:
        """Test case for update_comment_api_v1_secure_comments_put

        Update Comment
        """
        pass


if __name__ == '__main__':
    unittest.main()
