# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from litepolis_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_create_userprofile_api_v1_secure_users_profile_post(self) -> None:
        """Test case for create_userprofile_api_v1_secure_users_profile_post

        Create Userprofile
        """
        pass

    def test_delete_userprofile_api_v1_secure_users_profile_delete(self) -> None:
        """Test case for delete_userprofile_api_v1_secure_users_profile_delete

        Delete Userprofile
        """
        pass

    def test_get_testroute_api_v1_secure_get(self) -> None:
        """Test case for get_testroute_api_v1_secure_get

        Get Testroute
        """
        pass

    def test_get_userauth_api_v1_secure_users_auth_post(self) -> None:
        """Test case for get_userauth_api_v1_secure_users_auth_post

        Get Userauth
        """
        pass

    def test_get_userprofile_api_v1_secure_users_profile_get(self) -> None:
        """Test case for get_userprofile_api_v1_secure_users_profile_get

        Get Userprofile
        """
        pass

    def test_get_userrole_api_v1_secure_users_role_get(self) -> None:
        """Test case for get_userrole_api_v1_secure_users_role_get

        Get Userrole
        """
        pass

    def test_update_userprofile_api_v1_secure_users_profile_put(self) -> None:
        """Test case for update_userprofile_api_v1_secure_users_profile_put

        Update Userprofile
        """
        pass

    def test_update_usertoken_api_v1_secure_users_renew_put(self) -> None:
        """Test case for update_usertoken_api_v1_secure_users_renew_put

        Update Usertoken
        """
        pass


if __name__ == '__main__':
    unittest.main()
