CREATE DATABASE IF NOT EXISTS litepolis;

USE litepolis;

CREATE TABLE IF NOT EXISTS userdata (
    ID INT NOT NULL AUTO_INCREMENT,
    EMAIL STRING NOT NULL,
    PASSWORD STRING NOT NULL,
    PRIVILEGE STRING DEFAULT "user"
)
PRIMARY KEY (ID)
DISTRIBUTED BY HASH(ID);

CREATE TABLE IF NOT EXISTS conversationdata (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME STRING NOT NULL,
    DESCRIPTION STRING,
    CREATOR INT NOT NULL
);

CREATE TABLE IF NOT EXISTS commentsdata (
    ID INT NOT NULL AUTO_INCREMENT,
    CREATE_DATE DATETIME,
    COMMENT STRING NOT NULL,
    USERID INT NOT NULL,
    CONVERSATION INT NOT NULL,
    MODERATED BOOLEAN DEFAULT FALSE,
    APPROVED BOOLEAN DEFAULT FALSE
);
