# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from litepolis_client.models.comment_response_message import CommentResponseMessage
from litepolis_client.models.conversation_response_message import ConversationResponseMessage
from litepolis_client.models.user_response_message import UserResponseMessage
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

DETAIL2_ANY_OF_SCHEMAS = ["CommentResponseMessage", "ConversationResponseMessage", "UserResponseMessage", "str"]

class Detail2(BaseModel):
    """
    Detail2
    """

    # data type: str
    anyof_schema_1_validator: Optional[StrictStr] = None
    # data type: UserResponseMessage
    anyof_schema_2_validator: Optional[UserResponseMessage] = None
    # data type: ConversationResponseMessage
    anyof_schema_3_validator: Optional[ConversationResponseMessage] = None
    # data type: CommentResponseMessage
    anyof_schema_4_validator: Optional[CommentResponseMessage] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[CommentResponseMessage, ConversationResponseMessage, UserResponseMessage, str]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "CommentResponseMessage", "ConversationResponseMessage", "UserResponseMessage", "str" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = Detail2.model_construct()
        error_messages = []
        # validate data type: str
        try:
            instance.anyof_schema_1_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: UserResponseMessage
        if not isinstance(v, UserResponseMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserResponseMessage`")
        else:
            return v

        # validate data type: ConversationResponseMessage
        if not isinstance(v, ConversationResponseMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConversationResponseMessage`")
        else:
            return v

        # validate data type: CommentResponseMessage
        if not isinstance(v, CommentResponseMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CommentResponseMessage`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in Detail2 with anyOf schemas: CommentResponseMessage, ConversationResponseMessage, UserResponseMessage, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # deserialize data into str
        try:
            # validation
            instance.anyof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_1_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[UserResponseMessage] = None
        try:
            instance.actual_instance = UserResponseMessage.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[ConversationResponseMessage] = None
        try:
            instance.actual_instance = ConversationResponseMessage.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[CommentResponseMessage] = None
        try:
            instance.actual_instance = CommentResponseMessage.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Detail2 with anyOf schemas: CommentResponseMessage, ConversationResponseMessage, UserResponseMessage, str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CommentResponseMessage, ConversationResponseMessage, UserResponseMessage, str]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


